### ISSUE TITLE
Install package automatically with os.system!

### ISSUE THREAD

**Issue by timelessnesses** [tazz4843/DCustomRPC#2]
You could just make another python script and do something like this
```python
import os
pkglist = ["hentai","flask,"random_shit"]
for x in pkglist:
    os.system(f"pip install {x}")

```

**Comment by tazz4843** [comment]
i thought about doing this, but there's a lot of issues with pip on multiple systems

for one, `pip` won't always be in `PATH`, so that would end up throwing a error if it wasn't in path

two, `pip` on linux calls Python 2 not Python 3

three, `pip` on windows seems to be... shall we say unreliable.

in the end it's just easier to leave it up to the user instead of dealing with `pip` and OS nitpicks

**Comment by tazz4843** [comment]
on another note, even using `ensurepip` won't even work on certain linux systems, and linux is my single biggest priority since i run it, so that won't work either

**Comment by timelessnesses** [comment]
> on another note, even using `ensurepip` won't even work on certain linux systems, and linux is my single biggest priority since i run it, so that won't work either

@tazz4843 this should work?
```python
def find(filename,drive):
    for x in os.walk(drive):
        if filename in x:
            return x
        else:
            print(f"Can\'t find pip did you installed python yet or pip is somewhere else in drive?")
            return None
```

**Comment by tazz4843** [comment]
that would work, but it'd be slow as hell, on a SSD like mine it'd probably take 2 to 3 minutes at best, while on a HDD it'd probably take 10+ minutes depending on how many files exist and if they're indexed

you're basically looking through all of 25k+ files

**Comment by hydrostaticcog** [comment]
I wrote some code for McPy that installs pip, you could use something similar to this:
```
import logging
import sys
import subprocess

try: # Debian and Ubuntu require pip to be installed differently because they disable ensurepip
    import distro
    linuxDistro = distro.linux_distribution()
    if linuxDistro[0] == "Debian" or linuxDistro[0] == "Ubuntu":
        try:
            subprocess.check_call(['apt', 'install', 'python3-pip', '-y'])
        except subprocess.CalledProcessError:
            logging.fatal("You need to be the superuser to install pip and the dependencies")
            sys.exit(-4)
except ModuleNotFoundError: # If the system is not Linux, the module "distro" will not load, causing a ModuleNotFoundError exception and the normal "ensurepip" module will work
    subprocess.check_call([sys.executable, '-m', 'ensurepip']) # The module ensure pip check if pip is installed and installs it if it isn't
logging.info("Pip is installed")
```

**Comment by hydrostaticcog** [comment]
For some reason Debian-based distros disable the `ensurepip` module. All it does is give me headaches

**Comment by timelessnesses** [comment]
I am a windows user.
;-;

**Comment by hydrostaticcog** [comment]
Cool it will install pip using `ensurepip` module

**Comment by tazz4843** [comment]
> I wrote some code for McPy that installs pip, you could use something similar to this:
> 
> \~snip~

that's a viable solution, i'll look into adding all of this now

**Comment by hydrostaticcog** [comment]
Sounds good
